# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6dda1aaba9559b40da0bc5dd452c81d3e7e669a49a1495d6d43d4af8bd77603ed2d5014353955647441936b366ba548792756d93a15946071493304a8fb65fc

test:
  secret_key_base: c1ce67ec18ae78f9723aeaf347726be5a254d1434379687a368a3d9b14e314fbd1ae85fc1c841651060cce7ea19e7ccc8714f40380d12d0431fbfc261e7d4f73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
